### ISSUE TITLE
yanc dies while using TestId plugin and verbose output

### ISSUE THREAD

**Issue by jmoses** [0compute/yanc#7]
nosetests --with-yanc --with-id --collect-only -v test.py

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 304, in run
    result.startTest(self)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/proxy.py", line 169, in startTest
    self.plugins.startTest(self.test)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/testid.py", line 272, in startTest
    self.write('#%s ' % self.tests[adr])
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/plugins/testid.py", line 306, in write
    self.stream.write(output)
AttributeError: 'TestId' object has no attribute 'stream'
```

**Comment by deuxpi** [comment]
Can confirm on 0.3.3 (with nose 1.3.4). Could this be related to https://github.com/nose-devs/nose/issues/441 ?

**Comment by 0arthur** [comment]
Closing - fix in nose.
